#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from syntaxChecker.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "syntaxChecker.y"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "y.tab.h"
#include "semantic.h"

extern FILE *yyin;
extern int lineCount;
extern char *tablePtr;
extern char *tablePtr;
extern int nestedCommentCount;
extern int commentFlag;
extern int arrayIndexErr;
char *sourceCode=NULL;
int errorFlag=0;
void makeList(char *,char,int);



#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	AUTO	258
#define	BREAK	259
#define	CASE	260
#define	CHAR	261
#define	CONST	262
#define	CONTINUE	263
#define	DEFAULT	264
#define	DO	265
#define	DOUBLE	266
#define	ELSE	267
#define	ENUM	268
#define	GET	269
#define	SHOW	270
#define	EXTERN	271
#define	FLOAT	272
#define	FOR	273
#define	GOTO	274
#define	IF	275
#define	INT	276
#define	LONG	277
#define	REGISTER	278
#define	RETURN	279
#define	SHORT	280
#define	SIGNED	281
#define	SIZEOF	282
#define	STATIC	283
#define	STRUCT	284
#define	SWITCH	285
#define	TYPEDEF	286
#define	UNION	287
#define	UNSIGNED	288
#define	VOID	289
#define	VOLATILE	290
#define	WHILE	291
#define	IDENTIFIER	292
#define	CONSTANT	293
#define	FLCONSTANT	294
#define	STRING_LITERAL	295
#define	ELLIPSIS	296
#define	PTR_OP	297
#define	INC_OP	298
#define	DEC_OP	299
#define	LEFT_OP	300
#define	RIGHT_OP	301
#define	LE_OP	302
#define	GE_OP	303
#define	EQ_OP	304
#define	NE_OP	305
#define	AND_OP	306
#define	OR_OP	307
#define	MUL_ASSIGN	308
#define	DIV_ASSIGN	309
#define	MOD_ASSIGN	310
#define	ADD_ASSIGN	311
#define	SUB_ASSIGN	312
#define	LEFT_ASSIGN	313
#define	RIGHT_ASSIGN	314
#define	AND_ASSIGN	315
#define	XOR_ASSIGN	316
#define	OR_ASSIGN	317
#define	TYPE_NAME	318
#define	LOWER_THAN_ELSE	319


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int AUTO;
static const int BREAK;
static const int CASE;
static const int CHAR;
static const int CONST;
static const int CONTINUE;
static const int DEFAULT;
static const int DO;
static const int DOUBLE;
static const int ELSE;
static const int ENUM;
static const int GET;
static const int SHOW;
static const int EXTERN;
static const int FLOAT;
static const int FOR;
static const int GOTO;
static const int IF;
static const int INT;
static const int LONG;
static const int REGISTER;
static const int RETURN;
static const int SHORT;
static const int SIGNED;
static const int SIZEOF;
static const int STATIC;
static const int STRUCT;
static const int SWITCH;
static const int TYPEDEF;
static const int UNION;
static const int UNSIGNED;
static const int VOID;
static const int VOLATILE;
static const int WHILE;
static const int IDENTIFIER;
static const int CONSTANT;
static const int FLCONSTANT;
static const int STRING_LITERAL;
static const int ELLIPSIS;
static const int PTR_OP;
static const int INC_OP;
static const int DEC_OP;
static const int LEFT_OP;
static const int RIGHT_OP;
static const int LE_OP;
static const int GE_OP;
static const int EQ_OP;
static const int NE_OP;
static const int AND_OP;
static const int OR_OP;
static const int MUL_ASSIGN;
static const int DIV_ASSIGN;
static const int MOD_ASSIGN;
static const int ADD_ASSIGN;
static const int SUB_ASSIGN;
static const int LEFT_ASSIGN;
static const int RIGHT_ASSIGN;
static const int AND_ASSIGN;
static const int XOR_ASSIGN;
static const int OR_ASSIGN;
static const int TYPE_NAME;
static const int LOWER_THAN_ELSE;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,AUTO=258
	,BREAK=259
	,CASE=260
	,CHAR=261
	,CONST=262
	,CONTINUE=263
	,DEFAULT=264
	,DO=265
	,DOUBLE=266
	,ELSE=267
	,ENUM=268
	,GET=269
	,SHOW=270
	,EXTERN=271
	,FLOAT=272
	,FOR=273
	,GOTO=274
	,IF=275
	,INT=276
	,LONG=277
	,REGISTER=278
	,RETURN=279
	,SHORT=280
	,SIGNED=281
	,SIZEOF=282
	,STATIC=283
	,STRUCT=284
	,SWITCH=285
	,TYPEDEF=286
	,UNION=287
	,UNSIGNED=288
	,VOID=289
	,VOLATILE=290
	,WHILE=291
	,IDENTIFIER=292
	,CONSTANT=293
	,FLCONSTANT=294
	,STRING_LITERAL=295
	,ELLIPSIS=296
	,PTR_OP=297
	,INC_OP=298
	,DEC_OP=299
	,LEFT_OP=300
	,RIGHT_OP=301
	,LE_OP=302
	,GE_OP=303
	,EQ_OP=304
	,NE_OP=305
	,AND_OP=306
	,OR_OP=307
	,MUL_ASSIGN=308
	,DIV_ASSIGN=309
	,MOD_ASSIGN=310
	,ADD_ASSIGN=311
	,SUB_ASSIGN=312
	,LEFT_ASSIGN=313
	,RIGHT_ASSIGN=314
	,AND_ASSIGN=315
	,XOR_ASSIGN=316
	,OR_ASSIGN=317
	,TYPE_NAME=318
	,LOWER_THAN_ELSE=319


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::AUTO=258;
const int YY_parse_CLASS::BREAK=259;
const int YY_parse_CLASS::CASE=260;
const int YY_parse_CLASS::CHAR=261;
const int YY_parse_CLASS::CONST=262;
const int YY_parse_CLASS::CONTINUE=263;
const int YY_parse_CLASS::DEFAULT=264;
const int YY_parse_CLASS::DO=265;
const int YY_parse_CLASS::DOUBLE=266;
const int YY_parse_CLASS::ELSE=267;
const int YY_parse_CLASS::ENUM=268;
const int YY_parse_CLASS::GET=269;
const int YY_parse_CLASS::SHOW=270;
const int YY_parse_CLASS::EXTERN=271;
const int YY_parse_CLASS::FLOAT=272;
const int YY_parse_CLASS::FOR=273;
const int YY_parse_CLASS::GOTO=274;
const int YY_parse_CLASS::IF=275;
const int YY_parse_CLASS::INT=276;
const int YY_parse_CLASS::LONG=277;
const int YY_parse_CLASS::REGISTER=278;
const int YY_parse_CLASS::RETURN=279;
const int YY_parse_CLASS::SHORT=280;
const int YY_parse_CLASS::SIGNED=281;
const int YY_parse_CLASS::SIZEOF=282;
const int YY_parse_CLASS::STATIC=283;
const int YY_parse_CLASS::STRUCT=284;
const int YY_parse_CLASS::SWITCH=285;
const int YY_parse_CLASS::TYPEDEF=286;
const int YY_parse_CLASS::UNION=287;
const int YY_parse_CLASS::UNSIGNED=288;
const int YY_parse_CLASS::VOID=289;
const int YY_parse_CLASS::VOLATILE=290;
const int YY_parse_CLASS::WHILE=291;
const int YY_parse_CLASS::IDENTIFIER=292;
const int YY_parse_CLASS::CONSTANT=293;
const int YY_parse_CLASS::FLCONSTANT=294;
const int YY_parse_CLASS::STRING_LITERAL=295;
const int YY_parse_CLASS::ELLIPSIS=296;
const int YY_parse_CLASS::PTR_OP=297;
const int YY_parse_CLASS::INC_OP=298;
const int YY_parse_CLASS::DEC_OP=299;
const int YY_parse_CLASS::LEFT_OP=300;
const int YY_parse_CLASS::RIGHT_OP=301;
const int YY_parse_CLASS::LE_OP=302;
const int YY_parse_CLASS::GE_OP=303;
const int YY_parse_CLASS::EQ_OP=304;
const int YY_parse_CLASS::NE_OP=305;
const int YY_parse_CLASS::AND_OP=306;
const int YY_parse_CLASS::OR_OP=307;
const int YY_parse_CLASS::MUL_ASSIGN=308;
const int YY_parse_CLASS::DIV_ASSIGN=309;
const int YY_parse_CLASS::MOD_ASSIGN=310;
const int YY_parse_CLASS::ADD_ASSIGN=311;
const int YY_parse_CLASS::SUB_ASSIGN=312;
const int YY_parse_CLASS::LEFT_ASSIGN=313;
const int YY_parse_CLASS::RIGHT_ASSIGN=314;
const int YY_parse_CLASS::AND_ASSIGN=315;
const int YY_parse_CLASS::XOR_ASSIGN=316;
const int YY_parse_CLASS::OR_ASSIGN=317;
const int YY_parse_CLASS::TYPE_NAME=318;
const int YY_parse_CLASS::LOWER_THAN_ELSE=319;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		356
#define	YYFLAG		-32768
#define	YYNTBASE	89

#define YYTRANSLATE(x) ((unsigned)(x) <= 319 ? yytranslate[x] : 153)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    76,     2,     2,     2,    78,    71,     2,    65,
    66,    72,    73,    70,    74,    69,    77,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    84,    86,    79,
    85,    80,    83,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    67,     2,    68,    81,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    87,    82,    88,    75,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62,    63,    64
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     4,     6,     8,    11,    14,    18,    20,    25,
    29,    34,    38,    42,    45,    48,    50,    54,    56,    59,
    62,    65,    68,    69,    75,    77,    79,    81,    83,    85,
    87,    89,    94,    96,   100,   104,   108,   110,   114,   118,
   120,   124,   128,   130,   134,   138,   142,   146,   148,   152,
   156,   158,   162,   164,   168,   170,   174,   176,   180,   182,
   186,   188,   194,   196,   200,   202,   204,   206,   208,   210,
   212,   214,   216,   218,   220,   222,   224,   228,   230,   233,
   237,   239,   242,   244,   247,   249,   252,   254,   258,   260,
   264,   266,   268,   270,   272,   274,   276,   278,   280,   282,
   284,   286,   288,   290,   292,   294,   296,   298,   304,   309,
   312,   314,   316,   318,   321,   325,   328,   330,   333,   335,
   337,   341,   343,   346,   350,   355,   361,   364,   366,   370,
   372,   376,   378,   380,   383,   385,   387,   391,   396,   400,
   405,   410,   414,   416,   419,   422,   426,   428,   431,   433,
   437,   439,   443,   446,   449,   451,   453,   457,   459,   462,
   464,   466,   469,   473,   476,   480,   484,   489,   492,   496,
   500,   505,   507,   511,   516,   518,   522,   524,   526,   528,
   530,   532,   534,   538,   543,   547,   550,   554,   558,   563,
   565,   568,   570,   573,   575,   578,   584,   592,   598,   604,
   612,   619,   627,   631,   634,   637,   640,   644,   646,   649,
   651,   653,   658,   662,   666
};

static const short yyrhs[] = {    37,
     0,    39,     0,    38,     0,    40,     0,    15,    89,     0,
    14,    89,     0,    65,   109,    66,     0,    89,     0,    90,
    67,   109,    68,     0,    90,    65,    66,     0,    90,    65,
    91,    66,     0,    90,    69,    37,     0,    90,    42,    37,
     0,    90,    43,     0,    90,    44,     0,   107,     0,    91,
    70,   107,     0,    90,     0,    43,    92,     0,    44,    92,
     0,    94,    95,     0,    27,    92,     0,     0,    27,    65,
   136,    66,    93,     0,    71,     0,    72,     0,    73,     0,
    74,     0,    75,     0,    76,     0,    92,     0,    65,   136,
    66,    95,     0,    95,     0,    96,    72,    95,     0,    96,
    77,    95,     0,    96,    78,    95,     0,    96,     0,    97,
    73,    96,     0,    97,    74,    96,     0,    97,     0,    98,
    45,    97,     0,    98,    46,    97,     0,    98,     0,    99,
    79,    98,     0,    99,    80,    98,     0,    99,    47,    98,
     0,    99,    48,    98,     0,    99,     0,   100,    49,    99,
     0,   100,    50,    99,     0,   100,     0,   101,    71,   100,
     0,   101,     0,   102,    81,   101,     0,   102,     0,   103,
    82,   102,     0,   103,     0,   104,    51,   103,     0,   104,
     0,   105,    52,   104,     0,   105,     0,   105,    83,   109,
    84,   106,     0,   106,     0,    92,   108,   107,     0,    85,
     0,    53,     0,    54,     0,    55,     0,    56,     0,    57,
     0,    58,     0,    59,     0,    60,     0,    61,     0,    62,
     0,   107,     0,   109,    70,   107,     0,   106,     0,   112,
    86,     0,   112,   113,    86,     0,   115,     0,   115,   112,
     0,   116,     0,   116,   112,     0,   127,     0,   127,   112,
     0,   114,     0,   113,    70,   114,     0,   128,     0,   128,
    85,   139,     0,    31,     0,    16,     0,    28,     0,     3,
     0,    23,     0,    34,     0,     6,     0,    25,     0,    21,
     0,    22,     0,    17,     0,    11,     0,    26,     0,    33,
     0,   117,     0,   124,     0,    63,     0,   118,    37,    87,
   119,    88,     0,   118,    87,   119,    88,     0,   118,    37,
     0,    29,     0,    32,     0,   120,     0,   119,   120,     0,
   121,   122,    86,     0,   116,   121,     0,   116,     0,   127,
   121,     0,   127,     0,   123,     0,   122,    70,   123,     0,
   128,     0,    84,   110,     0,   128,    84,   110,     0,    13,
    87,   125,    88,     0,    13,    37,    87,   125,    88,     0,
    13,    37,     0,   126,     0,   125,    70,   126,     0,    37,
     0,    37,    85,   110,     0,     7,     0,    35,     0,   130,
   129,     0,   129,     0,    37,     0,    65,   128,    66,     0,
   129,    67,   110,    68,     0,   129,    67,    68,     0,   129,
    65,   132,    66,     0,   129,    65,   135,    66,     0,   129,
    65,    66,     0,    72,     0,    72,   131,     0,    72,   130,
     0,    72,   131,   130,     0,   127,     0,   131,   127,     0,
   133,     0,   133,    70,    41,     0,   134,     0,   133,    70,
   134,     0,   112,   128,     0,   112,   137,     0,   112,     0,
    37,     0,   135,    70,    37,     0,   121,     0,   121,   137,
     0,   130,     0,   138,     0,   130,   138,     0,    65,   137,
    66,     0,    67,    68,     0,    67,   110,    68,     0,   138,
    67,    68,     0,   138,    67,   110,    68,     0,    65,    66,
     0,    65,   132,    66,     0,   138,    65,    66,     0,   138,
    65,   132,    66,     0,   107,     0,    87,   140,    88,     0,
    87,   140,    70,    88,     0,   139,     0,   140,    70,   139,
     0,   142,     0,   143,     0,   146,     0,   147,     0,   148,
     0,   149,     0,    37,    84,   141,     0,     5,   110,    84,
   141,     0,     9,    84,   141,     0,    87,    88,     0,    87,
   145,    88,     0,    87,   144,    88,     0,    87,   144,   145,
    88,     0,   111,     0,   144,   111,     0,   141,     0,   145,
   141,     0,    86,     0,   109,    86,     0,    20,    65,   109,
    66,   141,     0,    20,    65,   109,    66,   141,    12,   141,
     0,    30,    65,   109,    66,   141,     0,    36,    65,   109,
    66,   141,     0,    10,   141,    36,    65,   109,    66,    86,
     0,    18,    65,   146,   146,    66,   141,     0,    18,    65,
   146,   146,   109,    66,   141,     0,    19,    37,    86,     0,
     8,    86,     0,     4,    86,     0,    24,    86,     0,    24,
   109,    86,     0,   151,     0,   150,   151,     0,   152,     0,
   111,     0,   112,   128,   144,   143,     0,   112,   128,   143,
     0,   128,   144,   143,     0,   128,   143,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    46,    47,    48,    49,    50,    51,    52,    55,    56,    57,
    58,    59,    60,    61,    62,    66,    67,    71,    72,    73,
    74,    75,    76,    77,    81,    82,    83,    84,    85,    86,
    90,    91,    95,    96,    97,    98,   102,   103,   104,   108,
   109,   110,   114,   115,   116,   117,   118,   122,   123,   124,
   128,   129,   133,   134,   138,   139,   143,   144,   148,   149,
   153,   154,   158,   159,   163,   164,   165,   166,   167,   168,
   169,   170,   171,   172,   173,   177,   178,   182,   186,   187,
   191,   192,   193,   194,   195,   196,   200,   201,   205,   206,
   210,   211,   212,   213,   214,   218,   219,   220,   221,   222,
   223,   224,   225,   226,   227,   228,   229,   233,   234,   235,
   239,   240,   244,   245,   249,   253,   254,   255,   256,   260,
   261,   265,   266,   267,   271,   272,   273,   277,   278,   282,
   283,   287,   288,   292,   293,   297,   298,   299,   300,   301,
   302,   303,   307,   308,   309,   310,   314,   315,   320,   321,
   325,   326,   330,   331,   332,   336,   337,   341,   342,   346,
   347,   348,   352,   353,   354,   355,   356,   357,   358,   359,
   360,   364,   365,   366,   370,   371,   375,   376,   377,   378,
   379,   380,   384,   385,   386,   390,   391,   392,   393,   397,
   398,   402,   403,   407,   408,   412,   414,   417,   422,   424,
   427,   429,   434,   435,   436,   437,   438,   442,   443,   447,
   448,   452,   453,   454,   455
};

static const char * const yytname[] = {   "$","error","$illegal.","AUTO","BREAK",
"CASE","CHAR","CONST","CONTINUE","DEFAULT","DO","DOUBLE","ELSE","ENUM","GET",
"SHOW","EXTERN","FLOAT","FOR","GOTO","IF","INT","LONG","REGISTER","RETURN","SHORT",
"SIGNED","SIZEOF","STATIC","STRUCT","SWITCH","TYPEDEF","UNION","UNSIGNED","VOID",
"VOLATILE","WHILE","IDENTIFIER","CONSTANT","FLCONSTANT","STRING_LITERAL","ELLIPSIS",
"PTR_OP","INC_OP","DEC_OP","LEFT_OP","RIGHT_OP","LE_OP","GE_OP","EQ_OP","NE_OP",
"AND_OP","OR_OP","MUL_ASSIGN","DIV_ASSIGN","MOD_ASSIGN","ADD_ASSIGN","SUB_ASSIGN",
"LEFT_ASSIGN","RIGHT_ASSIGN","AND_ASSIGN","XOR_ASSIGN","OR_ASSIGN","TYPE_NAME",
"LOWER_THAN_ELSE","'('","')'","'['","']'","'.'","','","'&'","'*'","'+'","'-'",
"'~'","'!'","'/'","'%'","'<'","'>'","'^'","'|'","'?'","':'","'='","';'","'{'",
"'}'","primary_expression","postfix_expression","argument_expression_list","unary_expression",
"@1","unary_operator","cast_expression","multiplicative_expression","additive_expression",
"shift_expression","relational_expression","equality_expression","and_expression",
"exclusive_or_expression","inclusive_or_expression","logical_and_expression",
"logical_or_expression","conditional_expression","assignment_expression","assignment_operator",
"expression","constant_expression","declaration","declaration_specifiers","init_declarator_list",
"init_declarator","storage_class_specifier","type_specifier","struct_or_union_specifier",
"struct_or_union","struct_declaration_list","struct_declaration","specifier_qualifier_list",
"struct_declarator_list","struct_declarator","enum_specifier","enumerator_list",
"enumerator","type_qualifier","declarator","direct_declarator","pointer","type_qualifier_list",
"parameter_type_list","parameter_list","parameter_declaration","identifier_list",
"type_name","abstract_declarator","direct_abstract_declarator","initializer",
"initializer_list","statement","labeled_statement","compound_statement","declaration_list",
"statement_list","expression_statement","selection_statement","iteration_statement",
"jump_statement","translation_unit","external_declaration","function_definition",
""
};
#endif

static const short yyr1[] = {     0,
    89,    89,    89,    89,    89,    89,    89,    90,    90,    90,
    90,    90,    90,    90,    90,    91,    91,    92,    92,    92,
    92,    92,    93,    92,    94,    94,    94,    94,    94,    94,
    95,    95,    96,    96,    96,    96,    97,    97,    97,    98,
    98,    98,    99,    99,    99,    99,    99,   100,   100,   100,
   101,   101,   102,   102,   103,   103,   104,   104,   105,   105,
   106,   106,   107,   107,   108,   108,   108,   108,   108,   108,
   108,   108,   108,   108,   108,   109,   109,   110,   111,   111,
   112,   112,   112,   112,   112,   112,   113,   113,   114,   114,
   115,   115,   115,   115,   115,   116,   116,   116,   116,   116,
   116,   116,   116,   116,   116,   116,   116,   117,   117,   117,
   118,   118,   119,   119,   120,   121,   121,   121,   121,   122,
   122,   123,   123,   123,   124,   124,   124,   125,   125,   126,
   126,   127,   127,   128,   128,   129,   129,   129,   129,   129,
   129,   129,   130,   130,   130,   130,   131,   131,   132,   132,
   133,   133,   134,   134,   134,   135,   135,   136,   136,   137,
   137,   137,   138,   138,   138,   138,   138,   138,   138,   138,
   138,   139,   139,   139,   140,   140,   141,   141,   141,   141,
   141,   141,   142,   142,   142,   143,   143,   143,   143,   144,
   144,   145,   145,   146,   146,   147,   147,   147,   148,   148,
   148,   148,   149,   149,   149,   149,   149,   150,   150,   151,
   151,   152,   152,   152,   152
};

static const short yyr2[] = {     0,
     1,     1,     1,     1,     2,     2,     3,     1,     4,     3,
     4,     3,     3,     2,     2,     1,     3,     1,     2,     2,
     2,     2,     0,     5,     1,     1,     1,     1,     1,     1,
     1,     4,     1,     3,     3,     3,     1,     3,     3,     1,
     3,     3,     1,     3,     3,     3,     3,     1,     3,     3,
     1,     3,     1,     3,     1,     3,     1,     3,     1,     3,
     1,     5,     1,     3,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     3,     1,     2,     3,
     1,     2,     1,     2,     1,     2,     1,     3,     1,     3,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     5,     4,     2,
     1,     1,     1,     2,     3,     2,     1,     2,     1,     1,
     3,     1,     2,     3,     4,     5,     2,     1,     3,     1,
     3,     1,     1,     2,     1,     1,     3,     4,     3,     4,
     4,     3,     1,     2,     2,     3,     1,     2,     1,     3,
     1,     3,     2,     2,     1,     1,     3,     1,     2,     1,
     1,     2,     3,     2,     3,     3,     4,     2,     3,     3,
     4,     1,     3,     4,     1,     3,     1,     1,     1,     1,
     1,     1,     3,     4,     3,     2,     3,     3,     4,     1,
     2,     1,     2,     1,     2,     5,     7,     5,     5,     7,
     6,     7,     3,     2,     2,     2,     3,     1,     2,     1,
     1,     4,     3,     3,     2
};

static const short yydefact[] = {     0,
    94,    97,   132,   102,     0,    92,   101,    99,   100,    95,
    98,   103,    93,   111,    91,   112,   104,    96,   133,   136,
   107,     0,   143,   211,     0,    81,    83,   105,     0,   106,
    85,     0,   135,     0,     0,   208,   210,   127,     0,     0,
   147,   145,   144,    79,     0,    87,    89,    82,    84,   110,
     0,    86,     0,   190,     0,   215,     0,     0,     0,   134,
   209,     0,   130,     0,   128,   137,   148,   146,     0,    80,
     0,   213,     0,     0,   117,     0,   113,     0,   119,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     1,     3,     2,     4,     0,     0,     0,
    25,    26,    27,    28,    29,    30,   194,   186,     8,    18,
    31,     0,    33,    37,    40,    43,    48,    51,    53,    55,
    57,    59,    61,    63,    76,     0,   192,   177,   178,     0,
     0,   179,   180,   181,   182,    89,   191,   214,   156,   142,
   155,     0,   149,   151,     0,     1,   139,    31,    78,     0,
     0,     0,     0,   125,    88,     0,   172,    90,   212,     0,
   116,   109,   114,     0,     0,   120,   122,   118,   205,     0,
   204,     0,     0,     0,     6,     5,     0,     0,     0,   206,
     0,     0,    22,     0,     0,     0,    19,    20,     0,   158,
     0,     0,    14,    15,     0,     0,     0,    66,    67,    68,
    69,    70,    71,    72,    73,    74,    75,    65,     0,    21,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
   195,   188,     0,   187,   193,     0,     0,   153,   160,   154,
   161,   140,     0,   141,     0,   138,   126,   131,   129,   175,
     0,   108,   123,     0,   115,     0,     0,   185,     0,     0,
   203,     0,   207,     0,     0,     0,   183,     7,     0,   160,
   159,     0,    13,    10,     0,    16,     0,    12,    64,    34,
    35,    36,    38,    39,    41,    42,    46,    47,    44,    45,
    49,    50,    52,    54,    56,    58,    60,     0,    77,   189,
   168,     0,     0,   164,     0,   162,     0,     0,   150,   152,
   157,     0,   173,   121,   124,   184,     0,     0,     0,    23,
     0,     0,    32,    11,     0,     9,     0,   169,   163,   165,
   170,     0,   166,     0,   174,   176,     0,     0,     0,   196,
    24,   198,   199,    17,    62,   171,   167,     0,   201,     0,
     0,   200,   202,   197,     0,     0
};

static const short yydefgoto[] = {   109,
   110,   275,   111,   341,   112,   113,   114,   115,   116,   117,
   118,   119,   120,   121,   122,   123,   124,   125,   209,   126,
   150,    54,    55,    45,    46,    26,    27,    28,    29,    76,
    77,    78,   165,   166,    30,    64,    65,    31,    32,    33,
    34,    43,   302,   143,   144,   145,   191,   303,   241,   158,
   251,   127,   128,   129,    57,   131,   132,   133,   134,   135,
    35,    36,    37
};

static const short yypact[] = {  1164,
-32768,-32768,-32768,-32768,   -23,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,    38,     5,-32768,     7,  1571,  1571,-32768,   -22,-32768,
  1571,   676,    86,    39,   812,-32768,-32768,   -58,    19,    12,
-32768,-32768,     5,-32768,    -1,-32768,   643,-32768,-32768,   -16,
   364,-32768,   329,-32768,     7,-32768,   676,  1209,  1275,    86,
-32768,    19,    -4,    13,-32768,-32768,-32768,-32768,    38,-32768,
   735,-32768,   676,   364,   364,   450,-32768,     8,   364,    60,
  1410,   115,     2,   717,    22,    22,    29,    68,   155,   842,
  1450,   182,   185,    55,-32768,-32768,-32768,  1464,  1464,   956,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   147,
   239,  1410,-32768,    71,   158,   195,   -27,   196,   154,   136,
   175,   177,   -20,-32768,-32768,    64,-32768,-32768,-32768,   415,
   490,-32768,-32768,-32768,-32768,   179,-32768,-32768,-32768,-32768,
   -18,   201,   206,-32768,    43,-32768,-32768,-32768,-32768,   214,
    49,  1410,    19,-32768,-32768,   735,-32768,-32768,-32768,   600,
-32768,-32768,-32768,  1410,    66,-32768,   199,-32768,-32768,   202,
-32768,   717,   251,  1410,-32768,-32768,   882,   216,  1410,-32768,
   109,   956,-32768,  1410,  1410,   717,-32768,-32768,   127,    73,
   222,   266,-32768,-32768,  1289,  1410,   268,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,  1410,-32768,
  1410,  1410,  1410,  1410,  1410,  1410,  1410,  1410,  1410,  1410,
  1410,  1410,  1410,  1410,  1410,  1410,  1410,  1410,  1410,  1410,
-32768,-32768,   565,-32768,-32768,  1030,  1330,-32768,    53,-32768,
   146,-32768,  1538,-32768,   271,-32768,-32768,-32768,-32768,-32768,
    54,-32768,-32768,     8,-32768,  1410,   717,-32768,   244,   882,
-32768,   128,-32768,   245,   137,   138,-32768,-32768,  1097,   162,
-32768,  1410,-32768,-32768,   152,-32768,   169,-32768,-32768,-32768,
-32768,-32768,    71,    71,   158,   158,   195,   195,   195,   195,
   -27,   -27,   196,   154,   136,   175,   177,    44,-32768,-32768,
-32768,   252,   254,-32768,   242,   146,  1245,  1344,-32768,-32768,
-32768,   241,-32768,-32768,-32768,-32768,  1410,  1396,   717,-32768,
   717,   717,-32768,-32768,  1410,-32768,  1410,-32768,-32768,-32768,
-32768,   255,-32768,   257,-32768,-32768,   153,   717,   160,   310,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,   237,-32768,   717,
   717,-32768,-32768,-32768,   326,-32768
};

static const short yypgoto[] = {   163,
-32768,-32768,   -57,-32768,-32768,   -96,    48,    56,   -34,    52,
   103,   105,   148,   104,   150,-32768,   -56,   -21,-32768,   -52,
   -64,    11,     0,-32768,   307,-32768,    23,-32768,-32768,   305,
   -69,   -70,-32768,   126,-32768,   320,   230,   159,   -12,   -33,
   -15,-32768,   -54,-32768,   141,-32768,   205,  -123,  -188,  -134,
-32768,   -61,-32768,    74,   -14,   258,  -171,-32768,-32768,-32768,
-32768,   356,-32768
};


#define	YYLAST		1634


static const short yytable[] = {    25,
    60,   148,   149,   142,   161,   260,   163,    42,   168,    40,
    24,     3,    47,    38,    50,   210,   170,   240,    20,   218,
   219,   250,   173,   148,   149,    48,    49,    68,    62,   190,
    52,   228,    73,   183,    25,    85,    86,   181,   130,    19,
   187,   188,   136,    20,    20,    24,   236,   189,   237,   157,
   306,   220,   221,    23,   148,    63,   136,   141,   146,    95,
    96,    97,   229,    39,    51,   167,   271,   137,    69,   235,
    74,    22,    22,    75,    20,    20,    23,    66,    23,    23,
   152,   306,   153,   137,    70,   172,   174,   248,   318,    20,
   163,   164,    44,   177,   148,   149,    75,    75,    75,   253,
   154,    75,    22,    22,   178,    56,   148,   149,   244,    23,
   258,   190,   245,   230,   280,   281,   282,   236,   153,   237,
    72,   189,    75,   312,   267,   239,   262,   327,   238,   189,
   138,   265,   266,   230,   157,   254,   247,   269,   186,   237,
   137,   313,   211,   277,    23,   169,   159,   212,   213,   231,
    58,   255,    59,   148,   148,   148,   148,   148,   148,   148,
   148,   148,   148,   148,   148,   148,   148,   148,   148,   148,
   148,   235,   305,   276,   270,   323,   298,   336,   230,   148,
   149,    41,    75,   287,   288,   289,   290,   279,   192,   193,
   194,   315,   268,   319,   263,   316,   230,   230,   148,   149,
   171,    67,   321,   322,    75,    60,   230,   230,   299,    79,
   307,   195,   308,   196,   148,   197,   225,   324,   348,   179,
   239,   325,   230,    40,   224,   350,   269,   227,   237,   230,
   214,   215,    79,    79,    79,   141,   326,    79,   230,   216,
   217,   167,   141,   334,   222,   223,   184,   175,   176,   185,
   148,   149,   332,   270,    85,    86,   226,   340,    79,   342,
   343,   283,   284,    71,   337,   339,   242,    91,   141,   148,
   345,   285,   286,   291,   292,   243,   349,   146,    95,    96,
    97,   246,   256,    98,    99,   257,   259,   272,   353,   354,
   157,   198,   199,   200,   201,   202,   203,   204,   205,   206,
   207,   261,   273,   344,   278,   100,   141,   311,   317,   330,
   320,   101,   102,   103,   104,   105,   106,   328,    79,   329,
   346,   351,   352,   208,   347,   356,   293,   156,   335,   294,
   296,     1,    80,    81,     2,     3,    82,    83,    84,     4,
    79,     5,    85,    86,     6,     7,    87,    88,    89,     8,
     9,    10,    90,    11,    12,    91,    13,    14,    92,    15,
    16,    17,    18,    19,    93,    94,    95,    96,    97,     2,
     3,    98,    99,   295,     4,   155,     5,   297,   160,   314,
     7,   151,   249,   310,     8,     9,   264,   233,    11,    12,
    61,    21,    14,   100,     0,    16,    17,    18,    19,   101,
   102,   103,   104,   105,   106,     0,     0,     0,     0,     0,
     0,     0,     0,     0,   107,    53,   108,     1,    80,    81,
     2,     3,    82,    83,    84,     4,    21,     5,    85,    86,
     6,     7,    87,    88,    89,     8,     9,    10,    90,    11,
    12,    91,    13,    14,    92,    15,    16,    17,    18,    19,
    93,    94,    95,    96,    97,     2,     3,    98,    99,     0,
     4,     0,     5,     0,     0,     0,     7,     0,     0,     0,
     8,     9,     0,     0,    11,    12,     0,    21,    14,   100,
     0,    16,    17,    18,    19,   101,   102,   103,   104,   105,
   106,     0,     0,    80,    81,     0,     0,    82,    83,    84,
   107,    53,   232,    85,    86,     0,     0,    87,    88,    89,
     0,     0,    21,    90,     0,     0,    91,     0,     0,    92,
     0,     0,     0,     0,     0,    93,    94,    95,    96,    97,
     0,     0,    98,    99,     0,     0,     0,   162,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,   100,     0,     0,     0,     0,     0,
   101,   102,   103,   104,   105,   106,     0,     0,    80,    81,
     0,     0,    82,    83,    84,   107,    53,   234,    85,    86,
     0,     0,    87,    88,    89,     0,     0,     0,    90,     0,
     0,    91,     0,     0,    92,     0,     0,     0,     0,     0,
    93,    94,    95,    96,    97,     2,     3,    98,    99,     0,
     4,     0,     5,     0,     0,     0,     7,     0,     0,     0,
     8,     9,     0,     0,    11,    12,     0,     0,    14,   100,
     0,    16,    17,    18,    19,   101,   102,   103,   104,   105,
   106,     0,     0,     0,     0,     1,     0,     0,     2,     3,
   107,    53,   300,     4,     0,     5,     0,     0,     6,     7,
     0,     0,    21,     8,     9,    10,     0,    11,    12,     0,
    13,    14,     0,    15,    16,    17,    18,    19,     1,     0,
     0,     2,     3,     0,     0,     0,     4,   252,     5,     0,
     0,     6,     7,     0,     0,     0,     8,     9,    10,     0,
    11,    12,     0,    13,    14,    21,    15,    16,    17,    18,
    19,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    80,    81,     0,     0,    82,    83,    84,    71,     0,    53,
    85,    86,     0,     0,    87,    88,    89,     0,    21,     0,
    90,     0,     0,    91,     0,     0,    92,     0,    85,    86,
     0,     0,    93,    94,    95,    96,    97,     0,     0,    98,
    99,    91,    53,     0,     0,     0,     0,     0,     0,     0,
     0,   146,    95,    96,    97,     0,     0,    98,    99,     0,
     0,   100,     0,     0,     0,     0,     0,   101,   102,   103,
   104,   105,   106,     0,     0,     0,     0,     0,     0,   100,
     0,     0,   107,    53,     0,   101,   102,   103,   104,   105,
   106,   355,     0,     0,     1,     0,     0,     2,     3,     0,
     0,   156,     4,     0,     5,     0,     0,     6,     7,     0,
     0,     0,     8,     9,    10,     0,    11,    12,     0,    13,
    14,     0,    15,    16,    17,    18,    19,     0,    20,     0,
     0,     0,     0,     0,     0,    85,    86,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,    91,     0,
     0,     0,     0,     0,    21,     0,    22,     0,   146,    95,
    96,    97,     0,    23,    98,    99,     0,     0,     0,     0,
     0,     0,     0,     0,     0,    85,    86,     0,     0,     0,
     0,     0,     0,     0,     0,     0,   100,     0,    91,     0,
     0,     0,   101,   102,   103,   104,   105,   106,   146,    95,
    96,    97,     0,     0,    98,    99,     0,   180,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,   100,     0,     0,     0,
     0,     0,   101,   102,   103,   104,   105,   106,     0,     0,
     0,     2,     3,     0,     0,     0,     4,   107,     5,    85,
    86,     0,     7,     0,     0,     0,     8,     9,     0,     0,
    11,    12,    91,     0,    14,     0,     0,    16,    17,    18,
    19,     0,   146,    95,    96,    97,     0,     0,    98,    99,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,    21,     0,
   100,     0,     0,     0,     0,     0,   101,   102,   103,   104,
   105,   106,     1,     0,     0,     2,     3,     0,     0,     0,
     4,     0,     5,     0,     0,     6,     7,     0,     0,     0,
     8,     9,    10,     0,    11,    12,     0,    13,    14,     0,
    15,    16,    17,    18,    19,     0,    20,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,    21,     0,   236,   301,   237,     0,     0,     1,
     0,    23,     2,     3,     0,     0,     0,     4,     0,     5,
     0,     0,     6,     7,     0,     0,     0,     8,     9,    10,
     0,    11,    12,     0,    13,    14,     0,    15,    16,    17,
    18,    19,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,    21,
     0,   269,   301,   237,     0,     0,     1,     0,    23,     2,
     3,     0,     0,     0,     4,     0,     5,     0,     0,     6,
     7,     0,     0,     0,     8,     9,    10,     0,    11,    12,
     0,    13,    14,     0,    15,    16,    17,    18,    19,     0,
    20,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     1,     0,     0,     2,     3,     0,     0,     0,     4,
     0,     5,     0,     0,     6,     7,    21,     0,    22,     8,
     9,    10,     0,    11,    12,    23,    13,    14,     0,    15,
    16,    17,    18,    19,     0,   139,     0,     1,     0,     0,
     2,     3,     0,     0,     0,     4,     0,     5,     0,     0,
     6,     7,     0,     0,     0,     8,     9,    10,     0,    11,
    12,    21,    13,    14,   140,    15,    16,    17,    18,    19,
     0,     0,     0,     0,     0,     0,     0,     0,    85,    86,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,    91,    85,    86,     0,     0,     0,    21,     0,     0,
   331,   146,    95,    96,    97,    91,     0,    98,    99,     0,
     0,     0,     0,     0,     0,   146,    95,    96,    97,     0,
     0,    98,    99,     0,     0,     0,     0,     0,     0,   100,
     0,     0,   147,    85,    86,   101,   102,   103,   104,   105,
   106,     0,     0,   100,   274,     0,    91,    85,    86,   101,
   102,   103,   104,   105,   106,     0,   146,    95,    96,    97,
    91,     0,    98,    99,     0,     0,     0,     0,     0,     0,
   146,    95,    96,    97,     0,     0,    98,    99,     0,     0,
     0,     0,     0,     0,   100,     0,     0,   304,     0,     0,
   101,   102,   103,   104,   105,   106,     0,     0,   100,    85,
    86,   333,     0,     0,   101,   102,   103,   104,   105,   106,
     0,     0,    91,    85,    86,     0,     0,     0,     0,     0,
     0,     0,   146,    95,    96,    97,    91,     0,    98,    99,
     0,     0,     0,     0,     0,     0,   146,    95,    96,    97,
     0,     0,    98,    99,     0,     0,     0,     0,     0,     0,
   100,   338,     0,    85,    86,     0,   101,   102,   103,   104,
   105,   106,     0,     0,   100,     0,    91,    85,    86,     0,
   101,   102,   103,   104,   105,   106,   146,    95,    96,    97,
    91,     0,    98,    99,     0,     0,     0,     0,     0,     0,
   146,    95,    96,    97,     0,     0,    98,    99,     0,     0,
     0,     0,     0,     0,   182,     0,     0,     0,     0,     0,
   101,   102,   103,   104,   105,   106,     0,     0,   174,     0,
     0,     0,     0,     0,   101,   102,   103,   104,   105,   106,
     1,     0,     0,     2,     3,     0,     0,     0,     4,     0,
     5,     0,     0,     6,     7,     0,     0,     0,     8,     9,
    10,     0,    11,    12,     0,    13,    14,     0,    15,    16,
    17,    18,    19,     1,     0,     0,     2,     3,   309,     0,
     0,     4,     0,     5,     0,     0,     6,     7,     0,     0,
     0,     8,     9,    10,     0,    11,    12,     0,    13,    14,
    21,    15,    16,    17,    18,    19,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    21
};

static const short yycheck[] = {     0,
    34,    59,    59,    58,    75,   177,    76,    23,    79,    22,
     0,     7,    25,    37,    37,   112,    81,   141,    37,    47,
    48,   156,    84,    81,    81,    26,    27,    43,    87,   100,
    31,    52,    47,    91,    35,    14,    15,    90,    53,    35,
    98,    99,    55,    37,    37,    35,    65,   100,    67,    71,
   239,    79,    80,    72,   112,    37,    69,    58,    37,    38,
    39,    40,    83,    87,    87,    78,   190,    57,    70,   131,
    87,    65,    65,    51,    37,    37,    72,    66,    72,    72,
    85,   270,    70,    73,    86,    84,    65,   152,   260,    37,
   160,    84,    86,    65,   152,   152,    74,    75,    76,   164,
    88,    79,    65,    65,    37,    32,   164,   164,    66,    72,
   172,   182,    70,    70,   211,   212,   213,    65,    70,    67,
    47,   174,   100,    70,   186,   141,   179,    84,   141,   182,
    57,   184,   185,    70,   156,    70,    88,    65,    84,    67,
   130,    88,    72,   196,    72,    86,    73,    77,    78,    86,
    65,    86,    67,   211,   212,   213,   214,   215,   216,   217,
   218,   219,   220,   221,   222,   223,   224,   225,   226,   227,
   228,   233,   237,   195,   190,   272,   229,   312,    70,   237,
   237,    23,   160,   218,   219,   220,   221,   209,    42,    43,
    44,   256,    66,    66,    86,   257,    70,    70,   256,   256,
    86,    43,    66,    66,   182,   239,    70,    70,   230,    51,
    65,    65,    67,    67,   272,    69,    81,    66,    66,    65,
   236,    70,    70,   236,    71,    66,    65,    51,    67,    70,
    73,    74,    74,    75,    76,   236,    68,    79,    70,    45,
    46,   254,   243,   308,    49,    50,    65,    85,    86,    65,
   308,   308,   307,   269,    14,    15,    82,   319,   100,   321,
   322,   214,   215,    85,   317,   318,    66,    27,   269,   327,
   327,   216,   217,   222,   223,    70,   338,    37,    38,    39,
    40,    68,    84,    43,    44,    84,    36,    66,   350,   351,
   312,    53,    54,    55,    56,    57,    58,    59,    60,    61,
    62,    86,    37,   325,    37,    65,   307,    37,    65,    68,
    66,    71,    72,    73,    74,    75,    76,    66,   160,    66,
    66,    12,    86,    85,    68,     0,   224,    87,    88,   225,
   227,     3,     4,     5,     6,     7,     8,     9,    10,    11,
   182,    13,    14,    15,    16,    17,    18,    19,    20,    21,
    22,    23,    24,    25,    26,    27,    28,    29,    30,    31,
    32,    33,    34,    35,    36,    37,    38,    39,    40,     6,
     7,    43,    44,   226,    11,    69,    13,   228,    74,   254,
    17,    62,   153,   243,    21,    22,   182,   130,    25,    26,
    35,    63,    29,    65,    -1,    32,    33,    34,    35,    71,
    72,    73,    74,    75,    76,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    86,    87,    88,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    63,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,     6,     7,    43,    44,    -1,
    11,    -1,    13,    -1,    -1,    -1,    17,    -1,    -1,    -1,
    21,    22,    -1,    -1,    25,    26,    -1,    63,    29,    65,
    -1,    32,    33,    34,    35,    71,    72,    73,    74,    75,
    76,    -1,    -1,     4,     5,    -1,    -1,     8,     9,    10,
    86,    87,    88,    14,    15,    -1,    -1,    18,    19,    20,
    -1,    -1,    63,    24,    -1,    -1,    27,    -1,    -1,    30,
    -1,    -1,    -1,    -1,    -1,    36,    37,    38,    39,    40,
    -1,    -1,    43,    44,    -1,    -1,    -1,    88,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    65,    -1,    -1,    -1,    -1,    -1,
    71,    72,    73,    74,    75,    76,    -1,    -1,     4,     5,
    -1,    -1,     8,     9,    10,    86,    87,    88,    14,    15,
    -1,    -1,    18,    19,    20,    -1,    -1,    -1,    24,    -1,
    -1,    27,    -1,    -1,    30,    -1,    -1,    -1,    -1,    -1,
    36,    37,    38,    39,    40,     6,     7,    43,    44,    -1,
    11,    -1,    13,    -1,    -1,    -1,    17,    -1,    -1,    -1,
    21,    22,    -1,    -1,    25,    26,    -1,    -1,    29,    65,
    -1,    32,    33,    34,    35,    71,    72,    73,    74,    75,
    76,    -1,    -1,    -1,    -1,     3,    -1,    -1,     6,     7,
    86,    87,    88,    11,    -1,    13,    -1,    -1,    16,    17,
    -1,    -1,    63,    21,    22,    23,    -1,    25,    26,    -1,
    28,    29,    -1,    31,    32,    33,    34,    35,     3,    -1,
    -1,     6,     7,    -1,    -1,    -1,    11,    88,    13,    -1,
    -1,    16,    17,    -1,    -1,    -1,    21,    22,    23,    -1,
    25,    26,    -1,    28,    29,    63,    31,    32,    33,    34,
    35,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
     4,     5,    -1,    -1,     8,     9,    10,    85,    -1,    87,
    14,    15,    -1,    -1,    18,    19,    20,    -1,    63,    -1,
    24,    -1,    -1,    27,    -1,    -1,    30,    -1,    14,    15,
    -1,    -1,    36,    37,    38,    39,    40,    -1,    -1,    43,
    44,    27,    87,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    37,    38,    39,    40,    -1,    -1,    43,    44,    -1,
    -1,    65,    -1,    -1,    -1,    -1,    -1,    71,    72,    73,
    74,    75,    76,    -1,    -1,    -1,    -1,    -1,    -1,    65,
    -1,    -1,    86,    87,    -1,    71,    72,    73,    74,    75,
    76,     0,    -1,    -1,     3,    -1,    -1,     6,     7,    -1,
    -1,    87,    11,    -1,    13,    -1,    -1,    16,    17,    -1,
    -1,    -1,    21,    22,    23,    -1,    25,    26,    -1,    28,
    29,    -1,    31,    32,    33,    34,    35,    -1,    37,    -1,
    -1,    -1,    -1,    -1,    -1,    14,    15,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    27,    -1,
    -1,    -1,    -1,    -1,    63,    -1,    65,    -1,    37,    38,
    39,    40,    -1,    72,    43,    44,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    14,    15,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    65,    -1,    27,    -1,
    -1,    -1,    71,    72,    73,    74,    75,    76,    37,    38,
    39,    40,    -1,    -1,    43,    44,    -1,    86,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    65,    -1,    -1,    -1,
    -1,    -1,    71,    72,    73,    74,    75,    76,    -1,    -1,
    -1,     6,     7,    -1,    -1,    -1,    11,    86,    13,    14,
    15,    -1,    17,    -1,    -1,    -1,    21,    22,    -1,    -1,
    25,    26,    27,    -1,    29,    -1,    -1,    32,    33,    34,
    35,    -1,    37,    38,    39,    40,    -1,    -1,    43,    44,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    63,    -1,
    65,    -1,    -1,    -1,    -1,    -1,    71,    72,    73,    74,
    75,    76,     3,    -1,    -1,     6,     7,    -1,    -1,    -1,
    11,    -1,    13,    -1,    -1,    16,    17,    -1,    -1,    -1,
    21,    22,    23,    -1,    25,    26,    -1,    28,    29,    -1,
    31,    32,    33,    34,    35,    -1,    37,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    63,    -1,    65,    66,    67,    -1,    -1,     3,
    -1,    72,     6,     7,    -1,    -1,    -1,    11,    -1,    13,
    -1,    -1,    16,    17,    -1,    -1,    -1,    21,    22,    23,
    -1,    25,    26,    -1,    28,    29,    -1,    31,    32,    33,
    34,    35,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    63,
    -1,    65,    66,    67,    -1,    -1,     3,    -1,    72,     6,
     7,    -1,    -1,    -1,    11,    -1,    13,    -1,    -1,    16,
    17,    -1,    -1,    -1,    21,    22,    23,    -1,    25,    26,
    -1,    28,    29,    -1,    31,    32,    33,    34,    35,    -1,
    37,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,     3,    -1,    -1,     6,     7,    -1,    -1,    -1,    11,
    -1,    13,    -1,    -1,    16,    17,    63,    -1,    65,    21,
    22,    23,    -1,    25,    26,    72,    28,    29,    -1,    31,
    32,    33,    34,    35,    -1,    37,    -1,     3,    -1,    -1,
     6,     7,    -1,    -1,    -1,    11,    -1,    13,    -1,    -1,
    16,    17,    -1,    -1,    -1,    21,    22,    23,    -1,    25,
    26,    63,    28,    29,    66,    31,    32,    33,    34,    35,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    14,    15,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    27,    14,    15,    -1,    -1,    -1,    63,    -1,    -1,
    66,    37,    38,    39,    40,    27,    -1,    43,    44,    -1,
    -1,    -1,    -1,    -1,    -1,    37,    38,    39,    40,    -1,
    -1,    43,    44,    -1,    -1,    -1,    -1,    -1,    -1,    65,
    -1,    -1,    68,    14,    15,    71,    72,    73,    74,    75,
    76,    -1,    -1,    65,    66,    -1,    27,    14,    15,    71,
    72,    73,    74,    75,    76,    -1,    37,    38,    39,    40,
    27,    -1,    43,    44,    -1,    -1,    -1,    -1,    -1,    -1,
    37,    38,    39,    40,    -1,    -1,    43,    44,    -1,    -1,
    -1,    -1,    -1,    -1,    65,    -1,    -1,    68,    -1,    -1,
    71,    72,    73,    74,    75,    76,    -1,    -1,    65,    14,
    15,    68,    -1,    -1,    71,    72,    73,    74,    75,    76,
    -1,    -1,    27,    14,    15,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    37,    38,    39,    40,    27,    -1,    43,    44,
    -1,    -1,    -1,    -1,    -1,    -1,    37,    38,    39,    40,
    -1,    -1,    43,    44,    -1,    -1,    -1,    -1,    -1,    -1,
    65,    66,    -1,    14,    15,    -1,    71,    72,    73,    74,
    75,    76,    -1,    -1,    65,    -1,    27,    14,    15,    -1,
    71,    72,    73,    74,    75,    76,    37,    38,    39,    40,
    27,    -1,    43,    44,    -1,    -1,    -1,    -1,    -1,    -1,
    37,    38,    39,    40,    -1,    -1,    43,    44,    -1,    -1,
    -1,    -1,    -1,    -1,    65,    -1,    -1,    -1,    -1,    -1,
    71,    72,    73,    74,    75,    76,    -1,    -1,    65,    -1,
    -1,    -1,    -1,    -1,    71,    72,    73,    74,    75,    76,
     3,    -1,    -1,     6,     7,    -1,    -1,    -1,    11,    -1,
    13,    -1,    -1,    16,    17,    -1,    -1,    -1,    21,    22,
    23,    -1,    25,    26,    -1,    28,    29,    -1,    31,    32,
    33,    34,    35,     3,    -1,    -1,     6,     7,    41,    -1,
    -1,    11,    -1,    13,    -1,    -1,    16,    17,    -1,    -1,
    -1,    21,    22,    23,    -1,    25,    26,    -1,    28,    29,
    63,    31,    32,    33,    34,    35,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    63
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 46 "syntaxChecker.y"
{ yyval=checkScope(tablePtr,lineCount); ;
    break;}
case 2:
#line 47 "syntaxChecker.y"
{tempCheckType=4;;
    break;}
case 3:
#line 48 "syntaxChecker.y"
{ addConstant(tablePtr, lineCount);;
    break;}
case 4:
#line 49 "syntaxChecker.y"
{ makeList(tablePtr, 's', lineCount);;
    break;}
case 5:
#line 50 "syntaxChecker.y"
{ makeList("show", 'k', lineCount);  ;
    break;}
case 6:
#line 51 "syntaxChecker.y"
{ makeList("get", 'k', lineCount);  ;
    break;}
case 7:
#line 52 "syntaxChecker.y"
{ makeList("(", 'p', lineCount); makeList(")", 'p', lineCount);;
    break;}
case 8:
#line 55 "syntaxChecker.y"
{yyval=yyvsp[0];;
    break;}
case 9:
#line 56 "syntaxChecker.y"
{ makeList("[", 'p', lineCount); makeList("]", 'p', lineCount); ;
    break;}
case 10:
#line 57 "syntaxChecker.y"
{ makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); ;
    break;}
case 11:
#line 58 "syntaxChecker.y"
{ makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); ;
    break;}
case 12:
#line 59 "syntaxChecker.y"
{ makeList(tablePtr, 'v', lineCount);;
    break;}
case 13:
#line 60 "syntaxChecker.y"
{ makeList(tablePtr, 'v', lineCount);;
    break;}
case 14:
#line 61 "syntaxChecker.y"
{ makeList(tablePtr, 'o', lineCount);;
    break;}
case 15:
#line 62 "syntaxChecker.y"
{ makeList(tablePtr, 'o', lineCount);;
    break;}
case 16:
#line 66 "syntaxChecker.y"
{;
    break;}
case 17:
#line 67 "syntaxChecker.y"
{ makeList(",",'p', lineCount); ;
    break;}
case 18:
#line 71 "syntaxChecker.y"
{;
    break;}
case 19:
#line 72 "syntaxChecker.y"
{ makeList("++",'o', lineCount); ;
    break;}
case 20:
#line 73 "syntaxChecker.y"
{ makeList("--",'o', lineCount);;
    break;}
case 22:
#line 75 "syntaxChecker.y"
{ makeList("sizeof",'o', lineCount); ;
    break;}
case 23:
#line 76 "syntaxChecker.y"
{ makeList("sizeof",'o', lineCount); ;
    break;}
case 24:
#line 77 "syntaxChecker.y"
{ makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); ;
    break;}
case 25:
#line 81 "syntaxChecker.y"
{ makeList("&",'o', lineCount);;
    break;}
case 26:
#line 82 "syntaxChecker.y"
{ makeList("*",'o', lineCount); ;
    break;}
case 27:
#line 83 "syntaxChecker.y"
{ makeList("+",'o', lineCount); ;
    break;}
case 28:
#line 84 "syntaxChecker.y"
{ makeList("-",'o', lineCount); ;
    break;}
case 29:
#line 85 "syntaxChecker.y"
{ makeList("~",'o', lineCount); ;
    break;}
case 30:
#line 86 "syntaxChecker.y"
{ makeList("!",'o', lineCount); ;
    break;}
case 31:
#line 90 "syntaxChecker.y"
{;
    break;}
case 32:
#line 91 "syntaxChecker.y"
{ makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); ;
    break;}
case 33:
#line 95 "syntaxChecker.y"
{;
    break;}
case 34:
#line 96 "syntaxChecker.y"
{ makeList("*",'o', lineCount); ;
    break;}
case 35:
#line 97 "syntaxChecker.y"
{ makeList("/",'o', lineCount); ;
    break;}
case 36:
#line 98 "syntaxChecker.y"
{ makeList("%",'o', lineCount); ;
    break;}
case 37:
#line 102 "syntaxChecker.y"
{;
    break;}
case 38:
#line 103 "syntaxChecker.y"
{ makeList("+",'o', lineCount); ;
    break;}
case 39:
#line 104 "syntaxChecker.y"
{ makeList("-",'o', lineCount); ;
    break;}
case 40:
#line 108 "syntaxChecker.y"
{;
    break;}
case 41:
#line 109 "syntaxChecker.y"
{ makeList("<<",'o', lineCount); ;
    break;}
case 42:
#line 110 "syntaxChecker.y"
{ makeList(">>",'o', lineCount); ;
    break;}
case 43:
#line 114 "syntaxChecker.y"
{;
    break;}
case 44:
#line 115 "syntaxChecker.y"
{;
    break;}
case 45:
#line 116 "syntaxChecker.y"
{;
    break;}
case 46:
#line 117 "syntaxChecker.y"
{ makeList("<=",'o', lineCount); ;
    break;}
case 47:
#line 118 "syntaxChecker.y"
{ makeList(">=",'o', lineCount); ;
    break;}
case 48:
#line 122 "syntaxChecker.y"
{;
    break;}
case 49:
#line 123 "syntaxChecker.y"
{ makeList("==",'o', lineCount); ;
    break;}
case 50:
#line 124 "syntaxChecker.y"
{ makeList("!=",'o', lineCount); ;
    break;}
case 51:
#line 128 "syntaxChecker.y"
{;
    break;}
case 52:
#line 129 "syntaxChecker.y"
{ makeList("&", 'o', lineCount); ;
    break;}
case 53:
#line 133 "syntaxChecker.y"
{;
    break;}
case 54:
#line 134 "syntaxChecker.y"
{ makeList("^", 'o', lineCount); ;
    break;}
case 55:
#line 138 "syntaxChecker.y"
{;
    break;}
case 56:
#line 139 "syntaxChecker.y"
{ makeList("|", 'o', lineCount); ;
    break;}
case 57:
#line 143 "syntaxChecker.y"
{;
    break;}
case 58:
#line 144 "syntaxChecker.y"
{ makeList("&&", 'o', lineCount); ;
    break;}
case 59:
#line 148 "syntaxChecker.y"
{;
    break;}
case 60:
#line 149 "syntaxChecker.y"
{ makeList("||", 'o', lineCount); ;
    break;}
case 61:
#line 153 "syntaxChecker.y"
{;
    break;}
case 62:
#line 154 "syntaxChecker.y"
{ makeList("?:",'o', lineCount); ;
    break;}
case 63:
#line 158 "syntaxChecker.y"
{;
    break;}
case 64:
#line 159 "syntaxChecker.y"
{ checkType(yyvsp[-2],yyvsp[0],lineCount);;
    break;}
case 65:
#line 163 "syntaxChecker.y"
{ makeList("=",'o', lineCount); ;
    break;}
case 66:
#line 164 "syntaxChecker.y"
{ makeList("*=",'o', lineCount); ;
    break;}
case 67:
#line 165 "syntaxChecker.y"
{ makeList("/=",'o', lineCount); ;
    break;}
case 68:
#line 166 "syntaxChecker.y"
{ makeList("%=",'o', lineCount); ;
    break;}
case 69:
#line 167 "syntaxChecker.y"
{ makeList("+=",'o', lineCount); ;
    break;}
case 70:
#line 168 "syntaxChecker.y"
{ makeList("-=",'o', lineCount); ;
    break;}
case 71:
#line 169 "syntaxChecker.y"
{ makeList("<<=",'o', lineCount); ;
    break;}
case 72:
#line 170 "syntaxChecker.y"
{ makeList(">=",'o', lineCount); ;
    break;}
case 73:
#line 171 "syntaxChecker.y"
{ makeList("&=",'o', lineCount); ;
    break;}
case 74:
#line 172 "syntaxChecker.y"
{ makeList("^=",'o', lineCount); ;
    break;}
case 75:
#line 173 "syntaxChecker.y"
{ makeList("|=",'o', lineCount); ;
    break;}
case 76:
#line 177 "syntaxChecker.y"
{;
    break;}
case 77:
#line 178 "syntaxChecker.y"
{ makeList(",", 'p', lineCount); ;
    break;}
case 79:
#line 186 "syntaxChecker.y"
{ makeList(";", 'p', lineCount);typeBuffer=' '; ;
    break;}
case 80:
#line 187 "syntaxChecker.y"
{ makeList(";", 'p', lineCount); typeBuffer=' ';;
    break;}
case 88:
#line 201 "syntaxChecker.y"
{ makeList(",", 'p', lineCount); ;
    break;}
case 90:
#line 206 "syntaxChecker.y"
{ makeList("=", 'o', lineCount); ;
    break;}
case 91:
#line 210 "syntaxChecker.y"
{ makeList("typedef", 'k', lineCount);;
    break;}
case 92:
#line 211 "syntaxChecker.y"
{ makeList("extern", 'k', lineCount);;
    break;}
case 93:
#line 212 "syntaxChecker.y"
{ makeList("static", 'k', lineCount);;
    break;}
case 94:
#line 213 "syntaxChecker.y"
{ makeList("auto", 'k', lineCount);;
    break;}
case 95:
#line 214 "syntaxChecker.y"
{ makeList("register", 'k', lineCount);;
    break;}
case 96:
#line 218 "syntaxChecker.y"
{ makeList("void", 'k', lineCount);typeBuffer='v';;
    break;}
case 97:
#line 219 "syntaxChecker.y"
{ makeList("char", 'k', lineCount); typeBuffer='c';;
    break;}
case 98:
#line 220 "syntaxChecker.y"
{ makeList("short", 'k', lineCount);;
    break;}
case 99:
#line 221 "syntaxChecker.y"
{ makeList("int", 'k', lineCount); typeBuffer='i';;
    break;}
case 100:
#line 222 "syntaxChecker.y"
{ makeList("long", 'k', lineCount);;
    break;}
case 101:
#line 223 "syntaxChecker.y"
{ makeList("float", 'k', lineCount);	typeBuffer='f';;
    break;}
case 102:
#line 224 "syntaxChecker.y"
{ makeList("double", 'k', lineCount);;
    break;}
case 103:
#line 225 "syntaxChecker.y"
{ makeList("signed", 'k', lineCount);;
    break;}
case 104:
#line 226 "syntaxChecker.y"
{ makeList("unsigned", 'k', lineCount);;
    break;}
case 111:
#line 239 "syntaxChecker.y"
{ makeList("struct", 'k', lineCount);;
    break;}
case 112:
#line 240 "syntaxChecker.y"
{ makeList("union", 'k', lineCount);;
    break;}
case 115:
#line 249 "syntaxChecker.y"
{ makeList(";", 'p', lineCount); ;
    break;}
case 121:
#line 261 "syntaxChecker.y"
{ makeList(",", 'p', lineCount); ;
    break;}
case 123:
#line 266 "syntaxChecker.y"
{ makeList(":", 'p', lineCount); ;
    break;}
case 124:
#line 267 "syntaxChecker.y"
{ makeList(":", 'p', lineCount); ;
    break;}
case 125:
#line 271 "syntaxChecker.y"
{ makeList("enum", 'k', lineCount);;
    break;}
case 126:
#line 272 "syntaxChecker.y"
{ makeList("enum", 'k', lineCount); makeList(tablePtr, 'v', lineCount); ;
    break;}
case 127:
#line 273 "syntaxChecker.y"
{ makeList("enum", 'k', lineCount); makeList(tablePtr, 'v', lineCount); ;
    break;}
case 129:
#line 278 "syntaxChecker.y"
{ makeList(",", 'p', lineCount); ;
    break;}
case 130:
#line 282 "syntaxChecker.y"
{ makeList(tablePtr, 'v', lineCount); ;
    break;}
case 131:
#line 283 "syntaxChecker.y"
{ makeList("=", 'o', lineCount); makeList("tablePtr", 'v', lineCount); ;
    break;}
case 132:
#line 287 "syntaxChecker.y"
{ makeList("const", 'k', lineCount); ;
    break;}
case 133:
#line 288 "syntaxChecker.y"
{ makeList("volatile", 'k', lineCount); ;
    break;}
case 136:
#line 297 "syntaxChecker.y"
{  checkDeclaration(tablePtr,lineCount,scopeCount);;
    break;}
case 137:
#line 298 "syntaxChecker.y"
{  makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); ;
    break;}
case 138:
#line 299 "syntaxChecker.y"
{ makeList("[", 'p', lineCount); makeList("]", 'p', lineCount); ;
    break;}
case 139:
#line 300 "syntaxChecker.y"
{ makeList("[", 'p', lineCount); makeList("]", 'p', lineCount); ;
    break;}
case 140:
#line 301 "syntaxChecker.y"
{ makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); ;
    break;}
case 141:
#line 302 "syntaxChecker.y"
{ makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); ;
    break;}
case 142:
#line 303 "syntaxChecker.y"
{ makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); ;
    break;}
case 143:
#line 307 "syntaxChecker.y"
{ makeList("*", 'o', lineCount); ;
    break;}
case 144:
#line 308 "syntaxChecker.y"
{ makeList("*", 'o', lineCount); ;
    break;}
case 145:
#line 309 "syntaxChecker.y"
{ makeList("*", 'o', lineCount); ;
    break;}
case 146:
#line 310 "syntaxChecker.y"
{ makeList("*", 'o', lineCount); ;
    break;}
case 150:
#line 321 "syntaxChecker.y"
{ makeList(",", 'p', lineCount); makeList("::", 'o', lineCount); ;
    break;}
case 152:
#line 326 "syntaxChecker.y"
{ makeList(",", 'p', lineCount); ;
    break;}
case 156:
#line 336 "syntaxChecker.y"
{ checkDeclaration(tablePtr,lineCount,scopeCount);;
    break;}
case 157:
#line 337 "syntaxChecker.y"
{ checkDeclaration(tablePtr,lineCount,scopeCount);makeList(",", 'p', lineCount); ;
    break;}
case 163:
#line 352 "syntaxChecker.y"
{ makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); ;
    break;}
case 164:
#line 353 "syntaxChecker.y"
{ makeList("[", 'p', lineCount); makeList("]", 'p', lineCount); ;
    break;}
case 165:
#line 354 "syntaxChecker.y"
{ makeList("[", 'p', lineCount); makeList("]", 'p', lineCount); ;
    break;}
case 166:
#line 355 "syntaxChecker.y"
{ makeList("[", 'p', lineCount); makeList("]", 'p', lineCount); ;
    break;}
case 167:
#line 356 "syntaxChecker.y"
{ makeList("[", 'p', lineCount); makeList("]", 'p', lineCount); ;
    break;}
case 168:
#line 357 "syntaxChecker.y"
{ makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); ;
    break;}
case 169:
#line 358 "syntaxChecker.y"
{ makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); ;
    break;}
case 170:
#line 359 "syntaxChecker.y"
{ makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); ;
    break;}
case 171:
#line 360 "syntaxChecker.y"
{ makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); ;
    break;}
case 172:
#line 364 "syntaxChecker.y"
{;
    break;}
case 176:
#line 371 "syntaxChecker.y"
{ makeList(",", 'p', lineCount); ;
    break;}
case 183:
#line 384 "syntaxChecker.y"
{ makeList(tablePtr, 'v', lineCount);  ;
    break;}
case 184:
#line 385 "syntaxChecker.y"
{ makeList(":", 'p', lineCount); makeList("case", 'k', lineCount);;
    break;}
case 185:
#line 386 "syntaxChecker.y"
{ makeList(":", 'p', lineCount); makeList("default", 'k', lineCount); ;
    break;}
case 194:
#line 407 "syntaxChecker.y"
{ makeList(";", 'p', lineCount); ;
    break;}
case 195:
#line 408 "syntaxChecker.y"
{ makeList(";", 'p', lineCount); ;
    break;}
case 196:
#line 413 "syntaxChecker.y"
{ makeList("if", 'k', lineCount); makeList("(", 'p', lineCount); makeList(")", 'p', lineCount);;
    break;}
case 197:
#line 415 "syntaxChecker.y"
{ makeList("if", 'k', lineCount);  makeList("else", 'k', lineCount); makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); 
  				;
    break;}
case 198:
#line 418 "syntaxChecker.y"
{ makeList("switch", 'k', lineCount); makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); ;
    break;}
case 199:
#line 423 "syntaxChecker.y"
{ makeList("while", 'k', lineCount); makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); ;
    break;}
case 200:
#line 425 "syntaxChecker.y"
{ makeList("do", 'k', lineCount); makeList("while", 'k', lineCount); makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); makeList(";", 'p', lineCount); 
			;
    break;}
case 201:
#line 428 "syntaxChecker.y"
{ makeList("for", 'k', lineCount); makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); ;
    break;}
case 202:
#line 430 "syntaxChecker.y"
{ makeList("for", 'k', lineCount); makeList("(", 'p', lineCount); makeList(")", 'p', lineCount); ;
    break;}
case 203:
#line 434 "syntaxChecker.y"
{ makeList("goto", 'k', lineCount); makeList(";", 'p', lineCount); makeList(tablePtr, 'v', lineCount);;
    break;}
case 204:
#line 435 "syntaxChecker.y"
{ makeList("continue", 'k', lineCount); makeList(";", 'p', lineCount); ;
    break;}
case 205:
#line 436 "syntaxChecker.y"
{ makeList("break", 'k', lineCount); makeList(";", 'p', lineCount);;
    break;}
case 206:
#line 437 "syntaxChecker.y"
{ makeList("return", 'k', lineCount); makeList(";", 'p', lineCount);;
    break;}
case 207:
#line 438 "syntaxChecker.y"
{ makeList("return", 'k', lineCount); makeList(";", 'p', lineCount);;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 458 "syntaxChecker.y"

void yyerror()
{
	errorFlag=1;
	fflush(stdout);
	printf("\n%s : %d :Syntax error \n",sourceCode,lineCount);
}
void main(int argc,char **argv){
	if(argc<=1){
		
		printf("Invalid ,Expected Format : ./a.out <\"sourceCode\"> \n");
		return 0;
	}
	
	yyin=fopen(argv[1],"r");
	sourceCode=(char *)malloc(strlen(argv[1])*sizeof(char));
	sourceCode=argv[1];
	
	yyparse();
	
	if(nestedCommentCount!=0){
		errorFlag=1;
    		printf("%s : %d : Comment Does Not End\n",sourceCode,lineCount);
    		
	}
	if(commentFlag==1){
		errorFlag=1;
		printf("%s : %d : Nested Comment\n",sourceCode,lineCount);
    	}
	if(!errorFlag  && !semanticErr  && arrayIndexErr!=1){
		
		printf("\n\n\t\t%s Parsing Completed\n\n",sourceCode);
		FILE *writeParsed=fopen("parsedTable.txt","w");
    		fprintf(writeParsed,"\n\t\t\t\tParsed Table\n\n\t\tToken\t\t\t\t\t\tType\t\t\t\t\t\t\tLine Number\n");
      		for(tokenList *ptr=parsedPtr;ptr!=NULL;ptr=ptr->next){
  			fprintf(writeParsed,"\n%20s%30.30s%60s",ptr->token,ptr->type,ptr->line);
		}
  		FILE *writeSymbol=fopen("symbolTable.txt","w");
    		fprintf(writeSymbol,"\n\t\t\t\tSymbolTable\n\n\t\tToken\t\t\t\tType\t\tLine Number\t\t\t\tScope\t\tFunction Number\n");
      		for(tokenList *ptr=symbolPtr;ptr!=NULL;ptr=ptr->next){
  			fprintf(writeSymbol,"\n%20s%30.30s%30s%30s\t%d\t%d",ptr->token,ptr->type,ptr->line,ptr->scope,ptr->scopeValue,ptr->funcCount+1);
		}
		
		FILE *writeConstant=fopen("constantTable.txt","w");
    		fprintf(writeConstant,"\n   \t\t\t\t\t\t\t\tConstant Table \n\n \t\t\t\t\t\tValue\t\t\t\t\t\t\tLine Number\n");
    		for(tokenList *ptr=constantPtr;ptr!=NULL;ptr=ptr->next)
  		fprintf(writeConstant,"\n%50s%60s",ptr->token,ptr->line);
  	        
  		fclose(writeSymbol);
		fclose(writeConstant);
		fclose(writeParsed);
		
printf("\n\n");	
}
     } 
     
